version: '3'

services: 
    localstack:
        container_name: localstack-localstack
        image: localstack/localstack:0.8.10
        hostname: localstack
        environment: 
            - SERVICES=sqs,sns,s3,dynamodb
            - HOSTNAME_EXTERNAL=localstack
        ports:
            - "4576:4576" # SQS
            - "4575:4575" # SNS
            - "4572:4572" # S3
            - "4569:4569" # dynamoDB
            - "8085:8080" # admin
        networks: 
            - custom
networks: 
    custom:
        driver: bridge
